# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import menu_digi.cloud_fix


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('avatar', menu_digi.cloud_fix.CloudinaryFieldFix(blank=True, max_length=255, null=True, verbose_name='image')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='restaurant.Restaurant')),
            ],
        ),
    ]
