# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
