# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20180812_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='restaurant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
