# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_foodcategory_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_category', to='restaurant.Restaurant'),
        ),
    ]
