# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20180812_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
