# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20180815_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
