# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 04:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_auto_20180820_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='foodids',
        ),
        migrations.AddField(
            model_name='order',
            name='order_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
