# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_auto_20180822_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
